### ISSUE TITLE
BurgerMenu Navigation

### ISSUE THREAD

**Issue by wintonmj** [wintonmj/burger-skeleton#13]
The template of the BurgerMenu is completed but functionality is missing. 

- [x] A bun Ingredient, when clicked on, should switch to the protein tab. The ingredient should highlight in case the user goes back to the buns page so they may see what they previously chose for when they wish to change the bun. 
- [x] A protein Ingredient, when clicked on, should switch to the Vegetable tab. The ingredient should highlight in case the user goes back to the protein page so they may see what they previously chose for when they wish to change the protein. 
- [x] A Vegetable Ingredient, when clicked on, should highlight for the duration of the creation of this burger. Users should be able to click on multiple veggies and then click a next button or another tab to change tab.
- [x] A Sauce Ingredient, when clicked on, should highlight for the duration of the creation of this burger. Users should be able to click on 2 sauces and then be redirected to the Extras tab. Users may also select only one or no sauces. 
- [x] An Extras Ingredient, when clicked on, should highlight for the duration of the creation of this burger. Users should be able to click on multiple Extras and then click a next button or another tab to change tab.
- [x] Finish. A finish button should be available in the BurgerMenu to show the burger is ready to add to the order. This button should be greyed out while a protein and bun have not been selected. 
_______________________________________________________________________________
Other things needed for BurgerMenu
- [x] Clear the temporary burger cash after the burger has been added to the order or canceled. This is for when the user creates another burger, the buttons are not highlighted still.

**Comment by Ethanol29** [comment]
Completed
